name: Make executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check directory location
        run: pwd
      - name: list files
        run: ls -laGh
      - name: build executable file
        run: gcc main.c -o main_x64
      - name: check generated files
        run: ls -laGh
      - uses: actions/upload-artifact@v2
        with:
          name: Ubuntu-x64
          path: /home/runner/work/janix_game/janix_game/main
  
  Windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: My location (pwd)
        shell: powershell
        run: pwd
      - name: list files
        shell: powershell
        run: ls
      - name: build executable file
        run: cl main.c
      - name: list builded files
        shell: powershell
        run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: Windows-x64
          path: D:\a\janix_game\janix_game\main.exe
